// <auto-generated />
namespace WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changeddefaulttablenames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeddefaulttablenames));
        
        string IMigrationMetadata.Id
        {
            get { return "201806071050524_changed default table names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
